In [1]:
print("Hellow world!")

Hellow world!


In [2]:
import numpy as np
def f01(start, end):
    sum =0
    for i in range(start, end+1):
        sum += i
    return sum

def f02(lt):
    M = lt[0]
    M = max(lt)
    for i in range(len(lt)):
        lt[i] = round(lt[i] / M, 2)
    return lt

def f03(n):
    a, b = 1,1
    lt = [a,b]
    for i in range(n):
        hap = a+b
        lt.append(hap)
        a, b= b, hap
    return lt
    
def f04(array, start, end):
    if start >= end: return
    pivot = start
    left, right = start + 1, end
    
    while left <= right:
        while left <= end and array[left] <= array[pivot]:
            left += 1
        while right > start and array[right] >= array[pivot]:
            right -= 1
        if left > right:
            array[right], array[pivot] = array[pivot], array[right]
        else:
            array[right], array[left] = array[left], array[right]


f04(array, start, right - 1)
f04(array, right + 1, end)





NameError: name 'array' is not defined

In [1]:
def f01(start, end):
    sum =0
    for i in range(start, end+1):
        sum += i
    return sum

In [12]:
import numpy as np
x = np.array([1,2,3,4])
y=x[:,np.newaxis]
print(y)
z=y.reshape(2,2)
print(z)
z[0] = 2
print(x)
print(y)
print(z)

[[1]
 [2]
 [3]
 [4]]
[[1 2]
 [3 4]]
[2 2 3 4]
[[2]
 [2]
 [3]
 [4]]
[[2 2]
 [3 4]]


In [27]:
x=np.array([[1,3,2],[5,4,6]])
print(np.sort(x,axis=1))

print(np.argsort(x,axis=1))

print(np.max(x,axis=1))

print(np.argmax(x,axis=1))

[[1 2 3]
 [4 5 6]]
[[0 2 1]
 [1 0 2]]
[3 6]
[1 2]


In [45]:
import numpy as np

a = np.array([1,2,3])

x =a[::2]

print(x.base)

a.dyty


[1 2 3]
