In [1]:
print("Hellow world!")

Hellow world!


In [2]:
import numpy as np
def f01(start, end):
    sum =0
    for i in range(start, end+1):
        sum += i
    return sum

def f02(lt):
    M = lt[0]
    M = max(lt)
    for i in range(len(lt)):
        lt[i] = round(lt[i] / M, 2)
    return lt

def f03(n):
    a, b = 1,1
    lt = [a,b]
    for i in range(n):
        hap = a+b
        lt.append(hap)
        a, b= b, hap
    return lt
    
def f04(array, start, end):
    if start >= end: return
    pivot = start
    left, right = start + 1, end
    
    while left <= right:
        while left <= end and array[left] <= array[pivot]:
            left += 1
        while right > start and array[right] >= array[pivot]:
            right -= 1
        if left > right:
            array[right], array[pivot] = array[pivot], array[right]
        else:
            array[right], array[left] = array[left], array[right]


f04(array, start, right - 1)
f04(array, right + 1, end)





NameError: name 'array' is not defined

In [1]:
def f01(start, end):
    sum =0
    for i in range(start, end+1):
        sum += i
    return sum

In [12]:
import numpy as np
x = np.array([1,2,3,4])
y=x[:,np.newaxis]
print(y)
z=y.reshape(2,2)
print(z)
z[0] = 2
print(x)
print(y)
print(z)

[[1]
 [2]
 [3]
 [4]]
[[1 2]
 [3 4]]
[2 2 3 4]
[[2]
 [2]
 [3]
 [4]]
[[2 2]
 [3 4]]


In [27]:
x=np.array([[1,3,2],[5,4,6]])
print(np.sort(x,axis=1))

print(np.argsort(x,axis=1))

print(np.max(x,axis=1))

print(np.argmax(x,axis=1))

[[1 2 3]
 [4 5 6]]
[[0 2 1]
 [1 0 2]]
[3 6]
[1 2]


In [45]:
import numpy as np

a = np.array([1,2,3])

x =a[::2]

print(x.base)

a.dyty


[1 2 3]


In [4]:
from calendar import c
from re import X
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
from pandas.core.arrays import StringArray
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.colors as mcols
import random
%matplotlib qt

plt.figure(figsize=(8, 8), dpi=80)
#--------------------------------
q1 =plt.subplot(2,2,1)
plt.title("( 3 )")
x = np.linspace(-1,2,100)
y1 =x*x
y2 =x
q1.plot(x, y1)
q1.plot(x, y2)
q1.fill_between(x,y1,y2, where=(x>0)&(x<1), alpha=0.5)
q1.grid(True)
q1.set_xticks([-1,0,1,2])


#-------------------------------------------

q2=plt.subplot(2,2,2)
plt.title("( 2 )")
x2 = np.linspace(2,6,100)
q2.set_yticks([6,8,10,12,14,16,18,20,22])
q2.set_xticks([3,4,5])
tcol = list(mcols.CSS4_COLORS)
count=1
data=np.genfromtxt("heightWeight.txt",skip_header=1)

for d in data:
    plt.scatter(d[0],d[1],color=tcol[len(tcol)-count])
    count+=1

#-------------------------------------------------------------

def f03(x,y):
    return (1 - x/2 + x**5 + y**3)*np.exp(-(x**2 + y**2))

q3=plt.subplot(2,2,3)
plt.title("( 3 )")

x=np.linspace(-3,3,256)
y=np.linspace(-3,3,256)
X,Y=np.meshgrid(x,y)
plt.imshow(f03(X, Y), extent=[0,250,0,250], cmap=plt.cm.jet)
plt.gca().invert_yaxis()
c = plt.contour(f03(X,Y),levels=15, linewidths=0.5, colors='k')
#cntr=plt.contourf(X,Y,f03(X,Y),levels=15, cmap=plt.cm.jet)
plt.clabel(c,inline=1,fontsize=10)

q3.set_xticks([0,50,100,150,200,250])
q3.set_yticks([250,200,150,100,50,0])
#-------------------------------------------
fig = plt.subplot(2,2,4)
plt.title("( 4 )")
ax = Axes3D(fig)
def f(x,y):
    return np.sin(x)*np.exp**-(x**2+y**2)
x = np.linspace(-3,3,100)
y = np.linspace(-3,3,100)
X, Y =np.meshgrid(x, y)

ax.set_zlim(-0.4,0.4)
ax.set_xticks([-2,0,2])
ax.set_yticks([-2,0,2])
ax.set_zticks([-0.4,-0.2,0,0.2,0.4])


ax.plot_surface(x,y,f(x,y), cmap='raindow', alpha=.5)
ax.contourf(x,y,f(x,y))
plt.show()


AttributeError: 'AxesSubplot' object has no attribute 'transSubfigure'

In [5]:
import numpy as np
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(8,8),dpi=80) # figure size는 80dpi, 8x8 inch로 설정

plt.subplot(2,2,1)
plt.title("( 1 )")
plt.xlim(-1*1.1,2*1.1)
plt.ylim(-1*1.1,4*1.1)
plt.grid()

x=np.linspace(-1,2,1000)
plt.plot(x,x**2)
plt.plot(x,x)
plt.fill_between(x,x,x**2,where =(x > x**2),alpha=.5)


q2=plt.subplot(2,2,2)
plt.title("( 2 )")
x2 = np.linspace(2,6,100)
q2.set_yticks([6,8,10,12,14,16,18,20,22])
q2.set_xticks([3,4,5])
tcol = list(mcols.CSS4_COLORS)
count=1
data=np.genfromtxt("heightWeight.txt",skip_header=1)

for d in data:
    plt.scatter(d[0],d[1],color=tcol[len(tcol)-count])
    count+=1

def f03(x,y):
    return (1 - x/2 + x**5 + y**3)*np.exp(-(x**2 + y**2))

q3=plt.subplot(2,2,3)
plt.title("( 3 )")

x=np.linspace(-3,3,256)
y=np.linspace(-3,3,256)
X,Y=np.meshgrid(x,y)
plt.imshow(f03(X, Y), extent=[0,250,0,250], cmap=plt.cm.jet)
plt.gca().invert_yaxis()
c = plt.contour(f03(X,Y),levels=15, linewidths=0.5, colors='k')
#cntr=plt.contourf(X,Y,f03(X,Y),levels=15, cmap=plt.cm.jet)
plt.clabel(c,inline=1,fontsize=10)

q3.set_xticks([0,50,100,150,200,250])
q3.set_yticks([250,200,150,100,50,0])
#------------------------------------------------------------------
from mpl_toolkits.mplot3d import Axes3D
ax = fig.add_subplot(2, 2, 4, projection='3d')
ax.set_title("( 4 )")
def f04(x,y):
    return np.sin(x)*np.exp(-(x**2 + y**2))

X = np.arange(-3, 3, 0.12)
Y = np.arange(-3, 3, 0.12)
X, Y = np.meshgrid(X, Y)
Z = f04(X,Y)

ax.plot_surface(X, Y, Z, rstride=1, cstride=1, cmap='rainbow', alpha=0.5)
ax.contourf(X, Y, Z, zdir='z', offset=-2, cmap='rainbow',alpha=0.5)
ax.set_zlim(-0.4, 0.4)
ax.set_xticks([-2,0,2])
ax.set_yticks([-2,0,2])
ax.set_zticks([-0.4,-0.2,0,0.2,0.4])
plt.show()